//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int IdDireccion { get; set; }
        public Nullable<int> IdDistribuidor { get; set; }
        public int IdComuna { get; set; }
        public int IdCliente { get; set; }
        public string Direccion1 { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Comuna Comuna { get; set; }
    }
}
