//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barCode.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle = new HashSet<Detalle>();
        }

        public int cantidad = 1;
        public int montoTotal = 0;
        public int total;
        public HttpPostedFileBase ImgFile { get; set; }

        public int IdProducto { get; set; }
        public string IdCategoria { get; set; }
        public string Foto { get; set; }
        public string NombreProd { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Stock { get; set; }
        public int Precio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public string Grado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
    }
}
